### ISSUE TITLE
release build failing

### ISSUE THREAD

**Issue by dirk-thomas** [tork-a/minas#61]
The latest binary jobs of `minas_control` are failing (see http://build.ros.org/view/Kbin_uX64/job/Kbin_uX64__minas_control__ubuntu_xenial_amd64__binary/6/). The reason is that the package is not declaring a dependency on TinyXML but was using TinyXML which was transitively provided by `rospack` in the past. `rospack` has recently been updated to a newer version of TinyXML (see ros/rospack#62) which makes this package fail.

The package should declare an explicit dependency on TinyXML and not rely on implicit transitive dependencies.

**Comment by 7675t** [comment]
Thanks @dirk-thomas , now it get back to normal.
