### ISSUE TITLE
I met issues when I installed this package

### ISSUE THREAD

**Issue by lmyhit** [tork-a/minas#64]
Hello, This error is below when I used catkin_make:

```
CMake Error at /opt/ros/kinetic/share/catkin/cmake/catkinConfig.cmake:83 (find_package):
  Could not find a package configuration file provided by "soem" with any of
  the following names:

    soemConfig.cmake
    soem-config.cmake

  Add the installation prefix of "soem" to CMAKE_PREFIX_PATH or set
  "soem_DIR" to a directory containing one of the above files.  If "soem"
  provides a separate development package or SDK, be sure it has been
  installed.
```
 And I tried to install the soem lib, but when I installed it successfully the errors were still existed. I found that the soem lib did not supply the config.cmake file.
How can I do to solve the problems, thanks very much!

**Comment by lmyhit** [comment]
I reinstalled the soem by 
`sudo apt-get install ros-kinetic-soem`
And it works.
This issue can be closed 
Thanks!

**Comment by 7675t** [comment]
Thanks for reporting. You can use rosdep: 
```
$ rosdep install -r --from-path src --ignore-src
```
to resolve all build dependency.

**Comment by iameijaz** [comment]
This would be a better and version-agnostic variant of the rosdep command, in case you are using an EOL distro of the ROS: 

`rosdep install -r --from-path src --ignore-src -y --rosdistro $ROS_DISTRO`

**Comment by iameijaz** [comment]
you can append -y at the end to avoid it from prompting you for installing each package:

`rosdep install -r --from-path src --ignore-src -y`
