### ISSUE TITLE
Feature request: publishing encoder value

### ISSUE THREAD

**Issue by 7675t** [tork-a/minas#65]
Hi, I think we need the feature to publish raw and offset encoder value to /encoder_state or something. It can be useful to acquire encoder offset in mechanical zero position. Right now we have to use PANATERM to get the offset value.

**Comment by 534o** [comment]
I have created #67 for this, but not sure what is your expected feature.
1. what cycle time  are you expecting? should we publish this every look? or 1 hz is ok? or others?
2. which topic should we use, for example JointStates? or others?

please see #67 and give us a feedback.

**Comment by 7675t** [comment]
#67 is looking good to me.

I think this feature is for introspection and debug, not for control. I didn't notice /diagnostics was published, but I agree it is reasonable to add the raw encoder value into the message. Then the cycle time is fixed to 1 Hz. I think it is enough for encoder calibration, because we can log the value while the robot is not in motion.
